### ISSUE TITLE
newspaper 0.2.8 with pythainlp

### ISSUE THREAD

**Issue by iwpnd** [will3216/newspaper3k_lambda_template#1]
Hi, any chance you've updated this build recently? Im baning my head against the wall on how to build the latest version with the pythainlp dependency for thai tokenization. Cheers

**Comment by will3216** [comment]
Seems the Dockerfile broke. Fixing it now

**Comment by will3216** [comment]
That was more of a pain than I anticipated, but I got it working. 
```bash
git clone git@github.com:will3216/newspaper3k_lambda_template.git
git checkout with_pythainlp
# Edit ./lib/newspaper_lambda.py
make
```
That will build your zip into your dist folder as newspaper_lambda.zip. Let me know if you run into any issues

**Comment by iwpnd** [comment]
Lol, I didn’t really expect an answer, much less a solution. Currently on mobile, but will test asap. Thank you!

**Comment by iwpnd** [comment]
Alright it build, thank you! Did you also run into problems with gcc/g++ during installation of marisa-trie? And is this the reason you use: `RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm` and `RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm`?

**Comment by iwpnd** [comment]
Amazing catch!

**Comment by will3216** [comment]
Haha, right? Well, I'm happy I could help. Gotta earn my stars! :D
